version: '3.8'
services:
  postgres:
    image: postgres:15.5-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - /Users/daughter/IdeaProjects/docker/postgresql/data:/var/lib/postgresql/data